# Generated by Django 4.0.6 on 2022-08-16 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_account_currency_customer_occupation_customer_pin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='loan',
            name='loan_number',
        ),
        migrations.AddField(
            model_name='card',
            name='signature',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='customer',
            name='signature',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_terms',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='currency',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='customer',
            name='age',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.PositiveIntegerField(),
        ),
    ]
