# Generated by Django 4.0.6 on 2022-08-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_customer_occupation_remove_loan_loan_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='Symbol',
            new_name='symbol',
        ),
    ]
